(deftheme tomorrow-night-bright
  "Created 2017-02-03.")

(custom-theme-set-variables
 'tomorrow-night-bright
 '(ansi-color-names-vector ["#eaeaea" "#d54e53" "#b9ca4a" "#e7c547" "#7aa6da" "#c397d8" "#70c0b1" "#000000"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'tomorrow-night-bright
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(outline-4 ((((class color) (min-colors 89)) (:slant normal :foreground "#969896"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896" :slant italic))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:underline "#e78c45" :background "#000000"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:underline "#d54e53" :background "#000000"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#7aa6da" :background "#000000" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#000000" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#000000" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#000000" :inherit font-lock-warning-face :inverse-video t))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#e78c45" :weight bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#000000"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#d54e53"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(linum ((t (:foreground "#808080"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(border ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#70c0b1"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#424242" :foreground "#eaeaea"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#2a2a2a" :foreground "#eaeaea"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#c397d8" :background nil))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(region ((((class color) (min-colors 89)) (:background "#424242"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c397d8" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#d54e53" :foreground "#e7c547"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#7aa6da" :foreground "#2a2a2a"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#e78c45" :foreground "#2a2a2a"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#424242"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:background "#2a2a2a" :foreground "#c397d8"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#b9ca4a" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#2a2a2a" :box (:line-width 1 :color "#eaeaea")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#7aa6da" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#2a2a2a"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#c397d8" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#e78c45" :height 1.44))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#2a2a2a"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#000000")))))

(provide-theme 'tomorrow-night-bright)
