(require 'racer)
(require 'rust-mode)
(require 'flycheck-rust)

;; (add-hook 'rust-mode-hook 'racer-mode)
(add-hook 'rust-mode-hook #'lsp)
(add-hook 'rust-mode-hook 'flycheck-mode)
(add-hook 'rust-mode-hook #'flycheck-rust-setup)
(add-hook 'rust-mode-hook 'company-mode)

(define-key rust-mode-map (kbd "C-x M-q")
  (lambda ()
    (interactive)
    (basic-save-buffer)
    (message projectile-project-root)
    (let ((curr-file-path (string-remove-prefix (projectile-project-root) buffer-file-name)))
      (cd (projectile-project-root))
      (shell-command "cargo +stable fmt")
      (revert-buffer nil t))))
