(setq custom--inhibit-theme-enable nil)

(custom-theme-set-faces
  'deeper-blue
  '(font-lock-comment-face ((t (:foreground "gray50" :slant italic))))
  '(font-lock-doc-face ((t (:foreground "#787878" :slant italic))))
  '(clojure-keyword-face ((t (:inherit font-lock-constant-face))))
  '(font-lock-constant-face ((t (:foreground "orange1"))))
  '(font-lock-type-face ((t (:foreground "gold"))))
  '(org-code ((t (:foreground "green yellow"))))
  '(ediff-even-diff-A ((t (:background "maroon"))))
  '(ediff-odd-diff-B ((t (:background "maroon"))))
  '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
  '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#7aa6da"))))
  '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
  '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#b9ca4a"))))
  '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
  '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#e78c45"))))
  '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
  '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
  '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
  '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
  )
